In [1]:
import numpy as np

In [6]:
a = np.random.randint(10, size=(10,))
b = np.random.randint(10, size=(10,))
print(a)
print(b)

[7 4 7 1 9 1 0 2 1 0]
[2 7 4 5 9 5 7 8 5 0]


In [17]:
idx = np.random.choice(range(0,10), size=5, replace =False)
print(idx)

[8 9 0 5 7]


In [18]:
print(a[idx])
print(b[idx])

[1 0 7 1 2]
[5 0 2 5 8]


In [19]:
print(str(None))

None


In [20]:
t = (1,2,3,4,5,6,7)

In [21]:
t[1:6]

(2, 3, 4, 5, 6)

In [40]:
VO = [-1.0, -0.1, 0.05]
a = -0.5
VO[np.argmin([abs(VO[0]-a), abs(VO[1]-a), abs(VO[2]-a)])]

-0.1